config/routes.rb
Rails.application.routes.draw do
  root to: 'post_cards#index'

  mount Lockup::Engine, at: '/lockup'

  localized do
    resources :post_cards,
      param: :slug
  end

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  get '/change_identity/', to: 'settings#change_identity', as: :change_identity

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_card.rb
# == Schema Information
#
# Table name: post_cards
#
#  id         :integer          not null, primary key
#  keywords   :text
#  slug       :text
#  image_url  :text
#  published  :boolean          not null
#  sent_at    :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostCard < ApplicationRecord

  def to_param
    slug
  end

  def next
    PostCard.where("sent_at > ?", sent_at).where(published: true).order(sent_at: :asc).limit(1).first
  end

  def prev
    PostCard.where("sent_at < ?", sent_at).where(published: true).order(sent_at: :desc).limit(1).first
  end

  translates :title, :body, :description
  validates :title, :image_url, :slug, :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  skip_before_action :check_for_lockup

  def set_locale
    if cookies[:educator_locale] && I18n.available_locales.include?(cookies[:educator_locale].to_sym)
      l = cookies[:educator_locale].to_sym
    else
      l = extract_locale_from_accept_language_header
      cookies.permanent[:educator_locale] = l
    end
    I18n.locale = l
  end

  private

  def extract_locale_from_accept_language_header
    if request.env['HTTP_ACCEPT_LANGUAGE'] &&
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first == 'en'
        return 'en'
    end
    'fr'
  end

end

app/controllers/post_cards_controller.rb
class PostCardsController < ApplicationController
  before_action :set_post_card, only: [:show, :edit, :update, :destroy]
  before_action :check_for_lockup, only: [:edit, :new]

  # GET /post_cards
  # GET /post_cards.json
  def index
    @post_cards = PostCard.all.where(published: true).order(sent_at: :desc)
  end

  # GET /post_cards/1
  # GET /post_cards/1.json
  def show
    @post_card = post_card
  end

  # GET /post_cards/new
  def new
    @post_card = PostCard.new
  end

  # GET /post_cards/1/edit
  def edit
  end

  # POST /post_cards
  # POST /post_cards.json
  def create
    @post_card = PostCard.new(post_card_params)

    respond_to do |format|
      if @post_card.save
        format.html { redirect_to @post_card, notice: 'PostCard was successfully created.' }
        format.json { render :show, status: :created, location: @post_card }
      else
        format.html { render :new }
        format.json { render json: @post_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_cards/1
  # PATCH/PUT /post_cards/1.json
  def update
    respond_to do |format|
      if @post_card.update(post_card_params)
        format.html { redirect_to @post_card, notice: 'PostCard was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_card }
      else
        format.html { render :edit }
        format.json { render json: @post_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_cards/1
  # DELETE /post_cards/1.json
  def destroy
    @post_card.destroy
    respond_to do |format|
      format.html { redirect_to post_cards_url, notice: 'PostCard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_card
      @post_card = PostCard.find_by!(slug: params[:slug])
    end

    def post_card
      @post_card ||= PostCard.find_by!(slug: params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_card_params
      params.require(:post_card).permit(:title, :keywords, :slug, :description, :image_url, :body, :sent_at, :published)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:educator_locale] = l
    redirect_to request.referer || root_url
  end

  def change_identity
    l_type = params[:email].to_s.strip.to_sym
    l_type = params[:type].to_s.strip.to_sym
    l_name = params[:name].to_s.strip.to_sym
    cookies.permanent[:leontiste_email] = l_email
    cookies.permanent[:leontiste_type] = l_type
    cookies.permanent[:leontiste_name] = l_name
    redirect_to request.referer || root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end

  def meta_tag(tag, text)
      content_for :"meta_#{tag}", text
  end

  def yield_meta_tag(tag, default_text='')
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end

end

app/helpers/post_cards_helper.rb
require 'nokogiri'

module PostCardsHelper
  def body_replaced(post_card)
    body = post_card.body
    # noko_bod = Nokogiri::HTML(body)
    # case cookies['leontiste_type']
    # when 'male', 'solo'
    #   noko_bod.search('.female').remove
    #   noko_bod.search('.group').remove
    # when 'female'
    #   noko_bod.search('.male').remove
    #   noko_bod.search('.group').remove
    # else
    #   noko_bod.search('.male').remove
    #   noko_bod.search('.female').remove
    # end
    # noko_bod.to_html.gsub!('$name', cookies['leontiste_name']).html_safe

    body.html_safe
  end
end

app/views/layouts/_footer.html.slim
/ footer
  .container
    .col-lg-10.col-md-10.col-sm-10.col-xs-12.offset-lg-1.offset-md-1
      .row
        .col-lg-6.col-md-6.col-sm-6.col-xs-12
            = link_to 'EN', change_locale_path(:en), class: 'block'
            = link_to 'FR', change_locale_path(:fr), class: 'block'


        / .col-lg-6.col-md-6.col-sm-6.col-xs-12
          a.block(href="#") Where are we?
          a.block(href="#") Follow us on Instagram

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-toggleable-sm.navbar-light.navbar-static-top
  .container
    .col-lg-10.col-md-10.col-sm-12.col-xs-12.offset-lg-1.offset-md-1
      .row
        .logo-block.col-lg-9.col-md-11.col-sm-12.col-xs-12
          h1 Leontiste
          a href="/"
            = image_tag('leon.png', alt: "Leon", id:'leon')
            = image_tag('middle.png', alt: "Middle", id:'middle')
            = image_tag('tiste.png', alt: "Tiste", id:'tiste')
        .col-lg-3.col-md-1.col-sm-12.col-xs-12.text-right
          / = link_to change_identity_path({"type" => "group", "name" => 'Baptiste'})
          = link_to change_locale_path(:en)
            = image_tag('queen_elizabeth.png', alt: t('menu.languages.en'), title: t('menu.languages.en'), class: 'align-top')
          = link_to change_locale_path(:fr)
            = image_tag('marianne.png', alt: t('menu.languages.fr'), title: t('menu.languages.fr'), class: 'align-top')

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta[name="description" content='#{yield_meta_tag(:description, 'Default description')}']
    meta[name="keywords" content='#{yield_meta_tag(:keywords, 'leontiste, postcard, voyage')}']

    title
      = if content_for?(:title) then yield(:title) + ' | '
      | Leontiste

    == csrf_meta_tags
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    == favicon_link_tag 'favicon.ico'
    == stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300|Lato:300,400", :media => 'all'
    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    == render 'layouts/navigation'
    .container
      .col-lg-10.col-md-10.col-sm-12.col-xs-12.offset-lg-1.offset-md-1
        = yield
    / == render 'layouts/footer'
    .modal.fade#img-modal(role='dialog')
      .modal-dialog.modal-lg
        .modal-content
          .modal-body

app/views/post_cards/_form.html.slim
= form_with(model: post_card, local: true) do |form|
  - if post_card.errors.any?
    #error_explanation
      h2
        = pluralize(post_card.errors.count, "error")
        | prohibited this post_card from being saved:
      ul
        - post_card.errors.full_messages.each do |message|
          li= message
  .form-group
    = form.label :title
    = form.text_field :title, id: :post_card_title, class: 'form-control'
  .form-group
    = form.label :keywords
    = form.text_field :keywords, id: :post_card_keywords, class: 'form-control'
  .form-group
    = form.label :slug
    = form.text_field :slug, id: :post_card_slug, class: 'form-control'
  .form-group
    = form.label :description
    = form.text_area :description, id: :post_card_description, class: 'form-control'
  .form-group
    = form.label :image_url
    = form.text_field :image_url, id: :post_card_image_url, class: 'form-control'
  .form-group
    = form.label :body
    = form.text_area :body, id: :post_card_body, class: 'form-control'
  .form-group
    = form.label :sent_at
    = form.datetime_select :sent_at, id: :post_card_sent_at, class: 'form-control'
  .form-group
    = form.label :published
    = form.check_box :published, id: :post_card_published, class: 'form-control'
  .actions
    = form.submit

app/views/post_cards/edit.html.slim
h1 Editing Post Card
= render 'form', post_card: @post_card
= link_to 'Show', @post_card

= link_to 'Back', post_cards_path

app/views/post_cards/index.html.slim
- title t('title.post_cards')
- meta_tag :description, 'Leontiste En Voyage'
- meta_tag :keywords, 'leontiste, voyage, nouvelle zelande, new zealand, kiwi'

p#notice= notice

p= t('index.headline1')
p= t('index.headline2')
p= t('index.headline3')

.row.mt-4
  - @post_cards.each do |post_card|
    .col-lg-4.col-md-4.col-sm-6.col-xs-12.mt-3
      = link_to post_card_path(post_card)
        = image_tag post_card.image_url, alt: post_card.title, title: post_card.title, class: 'img-fluid post_card_img'
        h1.mb-0= post_card.title
        p.mt-0= post_card.sent_at.strftime('%d/%m/%Y')

hr

.row.mb-4
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    h1.mb-3= t('index.where')
    .embed-responsive.embed-responsive-4by3
      iframe(class="embed-responsive-item" src="https://www.google.com/maps/d/embed?mid=19BKsQbuiEgd7QxHUEU2pCEqB7DHS_z0X")

app/views/post_cards/new.html.slim
h1 New Post Card
= render 'form', post_card: @post_card
= link_to 'Back', post_cards_path

app/views/post_cards/show.html.slim
- title @post_card.title
- meta_tag :description, @post_card.description
- meta_tag :keywords, @post_card.keywords

p#notice= notice
.col-lg-10.col-md-10.col-sm-10.col-xs-12.offset-lg-1.offset-md-1.mb-3.text-center
  = image_tag @post_card.image_url, alt: @post_card.title, title: @post_card.title, class: 'img-fluid post_card_img mb-2'

.col-lg-12.col-md-12.col-sm-12.col-xs-12.main-container.mb-4.rounded
  h1
    = @post_card.title

  .main-content
    = body_replaced(@post_card)

hr

h2= t('show.others')
.row
  / PREV POST CARD
  - if @post_card.prev
    .col-lg-6.col-md-6.col-sm-6.col-xs-12

      =link_to @post_card.prev
        h3.text-center
          i.fa.fa-chevron-left
          = t('show.previous_card')

        = image_tag @post_card.prev.image_url, alt: @post_card.prev.title, title: @post_card.prev.title, class: 'img-fluid post_card_img col-lg-6 col-md-6 col-sm-6 col-xs-12 offset-lg-3 offset-md-3 offset-sm-3 no-gutters-col'
        h1.text-center= @post_card.prev.title

  / NEXT POST CARD
  - if @post_card.next
    .col-lg-6.col-md-6.col-sm-6.col-xs-12

      =link_to @post_card.next
        h3.text-center
          = t('show.next_card')
          i.fa.fa-chevron-right

        = image_tag @post_card.next.image_url, alt: @post_card.next.title, title: @post_card.next.title, class: 'img-fluid post_card_img col-lg-6 col-md-6 col-sm-6 col-xs-12 offset-lg-3 offset-md-3 offset-sm-3 no-gutters-col'
        h1.text-center= @post_card.next.title